name: Python Lint and Test

on:
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install flake8
        python -m pip install pylint
        python -m pip install black
        python -m pip install pytest

    - name: Lint with flake8
      run: |
        python -m flake8 .

    - name: Lint with pylint
      run: |
        python -m pylint .

    - name: Format code with black
      run: |
        python -m black .

    - name: Run tests with pytest
      run: |
        python -m pytest --cov=my_module tests/
